version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(non-major deps):"
    labels:
      - "dependencies"
      - "minor-patch-updates"
    target-branch: "main"
  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(major deps):"
    labels:
      - "dependencies"
      - "major-update"
    target-branch: "main"

